/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiBaksoMalangCampurSari;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.SQLException;

/**
 *
 * @author LENOVO
 */
public class Aset extends javax.swing.JFrame {
    private DefaultTableModel tabelmode;
    private Connection Hub1 = new AplikasiBaksoMalangCampurSari().getData();

    /**
     * Creates new form Aset
     */
    public Aset() {
        initComponents();
        
        tabelmode = new DefaultTableModel();

        jTable1.setModel(tabelmode);

        tabelmode.addColumn("Kode");
        tabelmode.addColumn("Nama");
        tabelmode.addColumn("Tanggal Masuk");
        tabelmode.addColumn("Harga");
        tabelmode.addColumn("Jumlah");
        tabelmode.addColumn("TotalHarga");
        
        UP();
        datatable();
        Total();
        Tanggalan();
    }
        void Tanggalan(){
        TMasuk.setDate(new java.util.Date());
    }
            public void Angka(KeyEvent a){
       if(Character.isAlphabetic(a.getKeyChar())){
           a.consume();
           JOptionPane.showMessageDialog(null, "masukan angka saja!", "peringatan", JOptionPane.WARNING_MESSAGE);
       }
   }
    public void Hapus(){
            Kobar.setText("");
            Nabar.setText("");
            Harbar.setText("");
            Jumbar.setText("");
            Tanggalan();
        }
    public void UP(){
    try{
        String sql = "SELECT * FROM aset ORDER by KodeAset desc";
        Statement stat = Hub1.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        if (hasil.next()) {
            String ID = hasil.getString("KodeAset").substring(1);
            String angka = "" + (Integer.parseInt(ID) + 1);
            String kosong = "";
            Kobar.setText("A" + kosong + angka);
            } else {
            Kobar.setText("A1");
            }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
    }
    }
    public final void datatable(){
        tabelmode.getDataVector().removeAllElements();
        tabelmode.fireTableDataChanged();

        try {
            Statement s = Hub1.createStatement();
            String sql = "SELECT * FROM aset ORDER BY KodeAset DESC";
            Statement stat = Hub1.createStatement();
            ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()) {
                Object[] o = new Object[6];
                o[0] = hasil.getString("KodeAset");
                o[1] = hasil.getString("Nama");
                o[2] = hasil.getString("TanggalMasuk");
                o[3] = hasil.getString("Harga");
                o[4] = hasil.getString("Jumlah");
                o[5] = hasil.getString("TotalHarga");
                
                tabelmode.addRow(o);
            }
            hasil.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
    }

    private void Total (){
        try{
            String sql="SELECT SUM(`TotalHarga`) AS totalbiaya FROM aset";
            Statement stat = Hub1.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                jLabel8.setText(hasil.getString(""+"totalbiaya"));
            }
        } catch (SQLException e) 
        {System.out.println(e);}
    }
    private void refresh(){
DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
try{
  Statement stat = Hub1.createStatement();
    String sql="SELECT * FROM aset ORDER BY KodeAset DESC;";
    ResultSet hasil = stat.executeQuery(sql);
    while(hasil.next()){
      tabelmode.addRow(new Object[]{hasil.getString(1), hasil.getString(2), hasil.getString(3), hasil.getString(4), hasil.getString(5), hasil.getString(6)
});
    }
}catch(Exception e){
    System.out.print(e);
}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Nabar = new javax.swing.JTextField();
        Harbar = new javax.swing.JTextField();
        Jumbar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        CariT = new javax.swing.JTextField();
        Refresh = new javax.swing.JButton();
        Kobar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TMasuk = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel2.setText("Kode");

        jLabel3.setText("Tanggal Masuk");

        jLabel4.setText("Harga Barang");

        jLabel5.setText("Jumlah Barang");

        jLabel6.setText("Nama");

        Harbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HarbarKeyTyped(evt);
            }
        });

        Jumbar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JumbarKeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Hapus");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Tambah");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Ubah");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setText("Data Aset");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jButton4.setBackground(new java.awt.Color(255, 255, 51));
        jButton4.setText("Bersihkan");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        CariT.setText("Cari Nama atau Kode Barang");
        CariT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CariTKeyReleased(evt);
            }
        });

        Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/refresh-icon-clipart-transparent-3.png"))); // NOI18N
        Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshMouseClicked(evt);
            }
        });

        jLabel7.setText("Jumlah Uang :");

        jLabel9.setText("Cari Data :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Kobar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nabar, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(TMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Harbar, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(Jumbar)))
                    .addComponent(CariT, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Kobar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Nabar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Harbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(Jumbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addGap(9, 9, 9)
                                .addComponent(CariT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jButton1)
                                    .addComponent(jButton3)))
                            .addComponent(TMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int bar = jTable1.getSelectedRow();
        String KB = tabelmode.getValueAt(bar, 0).toString();
        String name = tabelmode.getValueAt(bar, 1).toString();
        String tanggal = tabelmode.getValueAt(bar, 2).toString();
        String hargaB = tabelmode.getValueAt(bar, 3).toString();
        String jumlah = tabelmode.getValueAt(bar, 4).toString();
        
        Kobar.setText(KB);
        Nabar.setText(name);
        try{
            String tampilan ="yyyy-MM-dd" ;
            SimpleDateFormat fm = new SimpleDateFormat(tampilan);
            java.util.Date z=fm.parse(tanggal);
            TMasuk.setDate(z);
        }catch(Exception ex){};
        Jumbar.setText(jumlah);
        Harbar.setText(hargaB);
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int hapus = JOptionPane.showConfirmDialog(null,"Yakin Untuk Menghapus?","Dialog Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (hapus==0){
            String sql = "DELETE FROM aset WHERE KodeAset='"+Kobar.getText()+"'";
            try{
                PreparedStatement stat = Hub1.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Terhapus");
                Hapus();
                UP();
                Kobar.requestFocus();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus"+e);
            }datatable();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked

        if(Nabar.getText().equals("") ||Harbar.getText().equals("") || Jumbar.getText().equals("")|| Kobar.getText().equals("")){
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
        int JB = (int) Double.parseDouble(Jumbar.getText());
        int HB = (int) Double.parseDouble(Harbar.getText());
        int Total = JB*HB;

        String tampilan ="yyyy-MM-dd" ;
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String date = String.valueOf(fm.format(TMasuk.getDate()));

        String sql = "INSERT INTO aset VALUES (?,?,?,?,?,?)";
        try{
            PreparedStatement stat = Hub1.prepareStatement(sql);

            stat.setString(1, Kobar.getText());
            stat.setString(2, Nabar.getText());
            stat.setString(3, date);
            stat.setInt(4, HB);
            stat.setInt(5, JB);
            stat.setInt(6, Total);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
            Hapus();
            UP();
            Kobar.requestFocus();

        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
        datatable();
Total();}// TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

        if(Nabar.getText().equals("") ||Harbar.getText().equals("") || Jumbar.getText().equals("")|| Kobar.getText().equals("")){
            JOptionPane.showMessageDialog(null, "LENGKAPI DATA !", "", JOptionPane.INFORMATION_MESSAGE);
        }else{
        int JB = (int) Double.parseDouble(Jumbar.getText());
        int HB = (int) Double.parseDouble(Harbar.getText());
        int Total = JB*HB;

        String tampilan ="yyyy-MM-dd" ;
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String date = String.valueOf(fm.format(TMasuk.getDate()));
        String sql = "UPDATE aset SET KodeAset=?,Nama=?,TanggalMasuk=?,Harga=?,Jumlah=?,TotalHarga=? WHERE KodeAset='"+Kobar.getText()+"'";
        try{
            PreparedStatement stat = Hub1.prepareStatement(sql);

            stat.setString(1, Kobar.getText());
            stat.setString(2, Nabar.getText());
            stat.setString(3, date);
            stat.setInt(4, HB);
            stat.setInt(5, JB);
            stat.setInt(6, Total);

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Terupdate");
            Hapus();
            UP();
            datatable();
            Kobar.requestFocus();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diupdate"+e);
        }
        datatable();
        Total();}
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Hapus();
        UP();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshMouseClicked
DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
while(model.getRowCount()>0){
    model.setRowCount(0);
}
refresh();
Hapus();
UP();// TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_RefreshMouseClicked

    private void CariTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CariTKeyReleased
        tabelmode.getDataVector().removeAllElements();
        tabelmode.fireTableDataChanged();
        String caridata = CariT.getText();

        try {
            Statement s = Hub1.createStatement();
            String sql = "SELECT * FROM aset WHERE KodeAset LIKE '%"+caridata+"%' OR Nama LIKE '%"+caridata+"%'order by KodeAset desc";
            Statement stat = Hub1.createStatement();
            ResultSet hasil = stat.executeQuery(sql);

            while (hasil.next()) {
                Object[] o = new Object[5];
                o[0] = hasil.getString("KodeAset");
                o[1] = hasil.getString("Nama");
                o[2] = hasil.getString("TanggalMasuk");
                o[3] = hasil.getString("Harga");
                o[4] = hasil.getString("Jumlah");
                
                
                tabelmode.addRow(o);
            }
            hasil.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error");
        }
        Hapus();
        UP();
        Total();        // TODO add your handling code here:
    }//GEN-LAST:event_CariTKeyReleased

    private void HarbarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HarbarKeyTyped
        // TODO add your handling code here:
        Angka(evt);
    }//GEN-LAST:event_HarbarKeyTyped

    private void JumbarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JumbarKeyTyped
        // TODO add your handling code here:
        Angka(evt);
    }//GEN-LAST:event_JumbarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aset.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aset().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CariT;
    private javax.swing.JTextField Harbar;
    private javax.swing.JTextField Jumbar;
    private javax.swing.JTextField Kobar;
    private javax.swing.JTextField Nabar;
    private javax.swing.JButton Refresh;
    private com.toedter.calendar.JDateChooser TMasuk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
